<?php

namespace Drupal\Tests\content_moderation\Kernel;

use Drupal\content_moderation\Permissions;
use Drupal\KernelTests\KernelTestBase;
use Drupal\simpletest\ContentTypeCreationTrait;
use Drupal\workflows\Entity\Workflow;

/**
 * Test to ensure content moderation permissions are generated correctly.
 *
 * @group content_moderation
 */
class ContentModerationPermissionsTest extends KernelTestBase {

  use ContentTypeCreationTrait;

  /**
   * Modules to install.
   *
   * @var array
   */
  public static $modules = [
    'workflows',
    'content_moderation',
    'workflow_type_test',
    'entity_test',
    'field',
    'node',
    'user',
    'text',
    'system',
  ];

  /**
   * {@inheritdoc}
   */
  protected function setUp() {
    parent::setUp();
    $this->installEntitySchema('workflow');
    $this->installEntitySchema('entity_test_no_bundle');
    $this->installEntitySchema('entity_test_rev');
    $this->installEntitySchema('node');
    $this->installEntitySchema('user');
    $this->installConfig(['node']);

    // Add 2 node types.
    $this->createContentType(['type' => 'foo', 'name' => 'Foo']);
    $this->createContentType(['type' => 'bar', 'name' => 'Bar']);
  }

  /**
   * Test permissions generated by content moderation.
   *
   * @dataProvider permissionsTestCases
   */
  public function testPermissions($workflow_definition, $transition_permissions, $unpublished_permissions = []) {
    /** @var \Drupal\workflows\WorkflowInterface $workflow */
    $workflow = Workflow::create($workflow_definition)->save();

    /** @var \Drupal\content_moderation\Permissions $permission_callback */
    $permission_callback = $this->container->get('class_resolver')
      ->getInstanceFromDefinition(Permissions::class);

    $this->assertEquals($transition_permissions, $permission_callback->transitionPermissions());
    $this->assertEquals($unpublished_permissions, $permission_callback->perBundleUnpublishedPermissions());
  }

  /**
   * Test cases for ::testPermissions
   *
   * @return array
   *   Content moderation permissions based test cases.
   */
  public function permissionsTestCases() {
    return [
      'Simple Content Moderation Workflow' => [
        [
          'id' => 'simple_workflow',
          'label' => 'Simple Workflow',
          'type' => 'content_moderation',
          'type_settings' => [
            'entity_types' => [
              // Types without per-bundle permission granularity will not
              // receive per-bundle permissions.
              'entity_test_no_bundle' => [
                'entity_test_no_bundle',
              ],
              'entity_test_rev' => [
                'entity_test_rev',
              ],
              'node' => [
                'foo',
                'bar',
              ],
            ],
          ],
        ],
        [
          'use simple_workflow transition publish' => [
            'title' => '<em class="placeholder">Simple Workflow</em> workflow: Use <em class="placeholder">Publish</em> transition.',
          ],
          'use simple_workflow transition create_new_draft' => [
            'title' => '<em class="placeholder">Simple Workflow</em> workflow: Use <em class="placeholder">Create New Draft</em> transition.',
          ],
        ],
        [
          'view any unpublished node:bar content' => [
            'title' => '<em class="placeholder">Content</em>: View any unpublished <em class="placeholder">Bar</em> content',
          ],
          'view any unpublished node:foo content' => [
            'title' => '<em class="placeholder">Content</em>: View any unpublished <em class="placeholder">Foo</em> content',
          ],
        ],
      ],
      'Non Content Moderation Workflow' => [
        [
          'id' => 'morning',
          'label' => 'Morning',
          'type' => 'workflow_type_test',
          'transitions' => [
            'drink_coffee' => [
              'label' => 'Drink Coffee',
              'from' => ['tired'],
              'to' => 'awake',
              'weight' => 0,
            ],
          ],
          'states' => [
            'awake' => [
              'label' => 'Awake',
              'weight' => -5,
            ],
            'tired' => [
              'label' => 'Tired',
              'weight' => -0,
            ],
          ],
        ],
        [],
        [],
      ],
    ];
  }

}
